### ISSUE TITLE
Issue with  Selenium::Screenshot install on Windows 

### ISSUE THREAD

**Issue by Chaoui05** [gempesaw/Selenium-Screenshot#1]
Hi everybody ! My question is simple. I would like to install Selenium::Screenshot to compare screenshots resulting from non regression tests. I already used Selenium::Remote::Driver which works with this package Selenium::Screenshot.
I followed the instructions as it mentioned in INSTALLATION section . But my install failed. I have the following issue in my Shell :

```
    --> Working on Selenium::Screenshot
    Fetching http://www.cpan.org/authors/id/G/GE/GEMPESAW/Selenium-Screenshot-0.07.tar.gz ... OK
    Configuring Selenium-Screenshot-0.07 ... OK
    Building and testing Selenium-Screenshot-0.07 ... FAIL
    ! Installing Selenium::Screenshot failed. See C:\Users\....\.cpanm\work\1463996479.13136\build.log for details. Retry with --force to force install it.
```

Anyone can help ? 

Many Thanks !

**Comment by gempesaw** [comment]
Ah, can you open the build.log file that `cpanm` creates and provide the output - is it about Imager::File::PNG installation failing?

The usual issue that I see is that the system cannot install Imager::File::PNG because it's missing the `libpng` dependency. [`Imager::Install`](https://metacpan.org/pod/Imager::Install#PNG---libpng) has some information about it - basically you want to be sure that you have `libpng` on your machine.

**Comment by xlat** [comment]
Hi,
in t/Screenshot.t, the $image_fh must be in binmode, otherwhise `\x0d\x0a` will be translated into \x0a and the png format will ne be recognized.

So add `binmode($image_fh)` just after `open (my $image_fh, "<", $sample_png) or die 'cannot open: ' . $!;`

**Comment by Chaoui05** [comment]
Hey ! Finally xlat resolved the issue. It works fine  now. Thanks everybody

**Comment by gempesaw** [comment]
Great, thanks :)
